# Generated by Django 4.0.1 on 2022-07-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(choices=[('CPF', 'pessoa fisica'), ('CNPJ', 'pessoa juridica')], max_length=100),
        ),
    ]
